### ISSUE TITLE
binary incompatibility C and python

### ISSUE THREAD

**Issue by geoHeil** [GiulioRossetti/cdlib#187]
**Describe the bug**

**To Reproduce**
- CDlib version: latest from pip
- Operating System: OsX: 10.15.7
- Python version: 3.8.8
- Version(s) of CDlib required libraries

```
from cdlib import algorithms
# requires
# brew install libom
import networkx as nx

G = nx.karate_club_graph()
coms = algorithms.infomap(G)
# fails with:
# ValueError: numpy.ndarray size changed, may indicate binary incompatibility. Expected 88 from C header, got 80 from PyObject
```

**Comment by Yquetzal** [comment]
Hi, do you have by any chance a new Mac with a Mac silicon (M1) chip ? I got a similar error on a different tool with those chips

**Comment by andrewhong5297** [comment]
I'm having the same issue, python 3.9.6 on Windows 10. I've tried going through this related issue for another repo but have had no luck (https://github.com/scikit-learn-contrib/hdbscan/issues/457).  

I don't know if this helps but when I try installing using `conda` instead of `pip` then I get this error:

```
(dev) C:\WINDOWS\system32>conda install cdlib
Collecting package metadata (current_repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.
Solving environment: failed with repodata from current_repodata.json, will retry with next repodata source.
Collecting package metadata (repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.
Solving environment: |
Found conflicts! Looking for incompatible packages.
This can take several minutes.  Press CTRL-C to abort.
Examining python=3.9:  60%|█████████████████████████████████████▏                        | 3/5 [00:00<00:00, 11.47it/s]\failed

UnsatisfiableError: The following specifications were found to be incompatible with each other:

Output in format: Requested package -> Available versions
```

And lastly if I try with `pip install --user cdlib` then I get this error instead `ImportError: cannot import name 'algorithms' from 'cdlib' (C:\Anaconda3\envs\dev\lib\site-packages\cdlib\__init__.py)`

**Comment by andrewhong5297** [comment]
adding some context from other answers I've seen, apparently, numpy >=1.20.0 solves this but cdlib requires 1.18.0

**Comment by geoHeil** [comment]
No it is a old one with an Intel CPU.

**Comment by geoHeil** [comment]
seems to work to force overwrite to a more recent version of numpy!

**Comment by GiulioRossetti** [comment]
@andrewhong5297 since v0.2.3 cdlib removed strict version dependencies for numpy in all it's distributions (pypi, conda, GitHub).

**Comment by Yquetzal** [comment]
@GiulioRossetti Actually I got a similar problem, cdlib was trying to force downgrade my numpy to 1.18, even with the latest version from GitHub.
I wonder if it is not because of one of the dependencies ? I searched quickly and notably I found that dynetx (https://github.com/GiulioRossetti/dynetx/blob/master/requirements.txt) impose a 1.18. Maybe that is the reason....

**Comment by GiulioRossetti** [comment]
That's strange: all tests CI/CI tests run smoothly for both pip and conda package. I'll look into dynetx. Have you tested on a clean environment as well?

**Comment by GiulioRossetti** [comment]
@Yquetzal I removed the strict dependency on numpy 1.18 from the pypi version of dynetx (it was already lifted from the conda version during the last release). 

In a few minutes, v0.2.8 of dynetx will be available on both conda and pip: if the problem was tied to such a dependency chain the issue should be now solved.

**Comment by Yquetzal** [comment]
> That's strange: all tests CI/CI tests run smoothly for both pip and conda package. I'll look into dynetx. Have you tested on a clean environment as well?

In my case, I just switched to a new M1 Mac, so yes clean environment but more than that, difficult to maintain since many packages need to be recompiled, including numpy, so when installing cdlib it was constantly failing because older versions of numpy could not be installed. I had to force install cdlib without dependencies and install them 1 by 1. I thought it was specific to my config, since I could not understand why It tried to downgrade numpy, but now it makes sense. 
I'll check if the problem is now solved.

**Comment by Yquetzal** [comment]
@GiulioRossetti apparently there is a problem in the version number because on pypi, the 0.2.77 is considered a later version than the 0.2.8 (see red flag https://pypi.org/project/dynetx/0.2.8/)
btw I user this tool `pipgrip --tree cdlib`  to see the dependendence tree, and I think that after that we will be all good :)

**Comment by GiulioRossetti** [comment]
There should be a mistake in one of the configuration files then - that's the lack of sleep having the upper end on me :-)

My bad, I'll fix it ASAP.

**Comment by andrewhong5297** [comment]
Okay the binary error is gone for me, now I get this when trying to from `cdlib import algorithms`

```
[autoreload of numpy.core.overrides failed: Traceback (most recent call last):
  File "C:\Anaconda3\envs\dev\lib\site-packages\IPython\extensions\autoreload.py", line 245, in check
    superreload(m, reload, self.old_objects)
  File "C:\Anaconda3\envs\dev\lib\site-packages\IPython\extensions\autoreload.py", line 394, in superreload
    module = reload(module)
  File "C:\Anaconda3\envs\dev\lib\imp.py", line 314, in reload
    return importlib.reload(module)
  File "C:\Anaconda3\envs\dev\lib\importlib\__init__.py", line 169, in reload
    _bootstrap._exec(spec, module)
  File "<frozen importlib._bootstrap>", line 613, in _exec
  File "<frozen importlib._bootstrap_external>", line 790, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "C:\Anaconda3\envs\dev\lib\site-packages\numpy\core\overrides.py", line 37, in <module>
    add_docstring(
RuntimeError: implement_array_function method already has a docstring
]
[autoreload of numpy.core.multiarray failed: Traceback (most recent call last):
  File "C:\Anaconda3\envs\dev\lib\site-packages\IPython\extensions\autoreload.py", line 245, in check
    superreload(m, reload, self.old_objects)
  File "C:\Anaconda3\envs\dev\lib\site-packages\IPython\extensions\autoreload.py", line 394, in superreload
    module = reload(module)
  File "C:\Anaconda3\envs\dev\lib\imp.py", line 314, in reload
    return importlib.reload(module)
  File "C:\Anaconda3\envs\dev\lib\importlib\__init__.py", line 169, in reload
    _bootstrap._exec(spec, module)
  File "<frozen importlib._bootstrap>", line 613, in _exec
  File "<frozen importlib._bootstrap_external>", line 790, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "C:\Anaconda3\envs\dev\lib\site-packages\numpy\core\multiarray.py", line 18, in <module>
    from ._multiarray_umath import (
ImportError: cannot import name '_set_madvise_hugepage' from 'numpy.core._multiarray_umath' (C:\Anaconda3\envs\dev\lib\site-packages\numpy\core\_multiarray_umath.cp39-win_amd64.pyd)
]
[autoreload of numpy.core._add_newdocs failed: Traceback (most recent call last):
  File "C:\Anaconda3\envs\dev\lib\site-packages\IPython\extensions\autoreload.py", line 245, in check
    superreload(m, reload, self.old_objects)
  File "C:\Anaconda3\envs\dev\lib\site-packages\IPython\extensions\autoreload.py", line 394, in superreload
    module = reload(module)
  File "C:\Anaconda3\envs\dev\lib\imp.py", line 314, in reload
    return importlib.reload(module)
  File "C:\Anaconda3\envs\dev\lib\importlib\__init__.py", line 169, in reload
    _bootstrap._exec(spec, module)
  File "<frozen importlib._bootstrap>", line 613, in _exec
  File "<frozen importlib._bootstrap_external>", line 790, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "C:\Anaconda3\envs\dev\lib\site-packages\numpy\core\_add_newdocs.py", line 4443, in <module>
    add_newdoc('numpy.core.multiarray', '_set_madvise_hugepage',
  File "C:\Anaconda3\envs\dev\lib\site-packages\numpy\core\function_base.py", line 521, in add_newdoc
    new = getattr(__import__(place, globals(), {}, [obj]), obj)
AttributeError: module 'numpy.core.multiarray' has no attribute '_set_madvise_hugepage'
]
[autoreload of numpy.matrixlib failed: Traceback (most recent call last):
  File "C:\Anaconda3\envs\dev\lib\site-packages\IPython\extensions\autoreload.py", line 245, in check
    superreload(m, reload, self.old_objects)
  File "C:\Anaconda3\envs\dev\lib\site-packages\IPython\extensions\autoreload.py", line 394, in superreload
    module = reload(module)
  File "C:\Anaconda3\envs\dev\lib\imp.py", line 314, in reload
    return importlib.reload(module)
  File "C:\Anaconda3\envs\dev\lib\importlib\__init__.py", line 169, in reload
    _bootstrap._exec(spec, module)
  File "<frozen importlib._bootstrap>", line 613, in _exec
  File "<frozen importlib._bootstrap_external>", line 790, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "C:\Anaconda3\envs\dev\lib\site-packages\numpy\matrixlib\__init__.py", line 6, in <module>
    __all__ = defmatrix.__all__
NameError: name 'defmatrix' is not defined
]
[autoreload of numpy.lib failed: Traceback (most recent call last):
  File "C:\Anaconda3\envs\dev\lib\site-packages\IPython\extensions\autoreload.py", line 245, in check
    superreload(m, reload, self.old_objects)
  File "C:\Anaconda3\envs\dev\lib\site-packages\IPython\extensions\autoreload.py", line 394, in superreload
    module = reload(module)
  File "C:\Anaconda3\envs\dev\lib\imp.py", line 314, in reload
    return importlib.reload(module)
  File "C:\Anaconda3\envs\dev\lib\importlib\__init__.py", line 169, in reload
    _bootstrap._exec(spec, module)
  File "<frozen importlib._bootstrap>", line 613, in _exec
  File "<frozen importlib._bootstrap_external>", line 790, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "C:\Anaconda3\envs\dev\lib\site-packages\numpy\lib\__init__.py", line 44, in <module>
    __all__ += type_check.__all__
NameError: name 'type_check' is not defined
]
[autoreload of numpy.random failed: Traceback (most recent call last):
  File "C:\Anaconda3\envs\dev\lib\site-packages\IPython\extensions\autoreload.py", line 245, in check
    superreload(m, reload, self.old_objects)
  File "C:\Anaconda3\envs\dev\lib\site-packages\IPython\extensions\autoreload.py", line 394, in superreload
    module = reload(module)
  File "C:\Anaconda3\envs\dev\lib\imp.py", line 314, in reload
    return importlib.reload(module)
  File "C:\Anaconda3\envs\dev\lib\importlib\__init__.py", line 169, in reload
    _bootstrap._exec(spec, module)
  File "<frozen importlib._bootstrap>", line 613, in _exec
  File "<frozen importlib._bootstrap_external>", line 790, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "C:\Anaconda3\envs\dev\lib\site-packages\numpy\random\__init__.py", line 184, in <module>
    from .bit_generator import SeedSequence, BitGenerator
  File "bit_generator.pyx", line 1, in init numpy.random.bit_generator
ValueError: numpy.ndarray size changed, may indicate binary incompatibility. Expected 88 from C header, got 80 from PyObject
]
[autoreload of numpy.ma.core failed: Traceback (most recent call last):
  File "C:\Anaconda3\envs\dev\lib\site-packages\IPython\extensions\autoreload.py", line 245, in check
    superreload(m, reload, self.old_objects)
  File "C:\Anaconda3\envs\dev\lib\site-packages\IPython\extensions\autoreload.py", line 410, in superreload
    update_generic(old_obj, new_obj)
  File "C:\Anaconda3\envs\dev\lib\site-packages\IPython\extensions\autoreload.py", line 347, in update_generic
    update(a, b)
  File "C:\Anaconda3\envs\dev\lib\site-packages\IPython\extensions\autoreload.py", line 292, in update_class
    if (old_obj == new_obj) is True:
  File "C:\Anaconda3\envs\dev\lib\site-packages\numpy\ma\core.py", line 4112, in __eq__
    return self._comparison(other, operator.eq)
  File "C:\Anaconda3\envs\dev\lib\site-packages\numpy\ma\core.py", line 4050, in _comparison
    mask = mask_or(smask, omask, copy=True)
  File "C:\Anaconda3\envs\dev\lib\site-packages\numpy\ma\core.py", line 1753, in mask_or
    return make_mask(umath.logical_or(m1, m2), copy=copy, shrink=shrink)
  File "C:\Anaconda3\envs\dev\lib\site-packages\numpy\ma\core.py", line 1635, in make_mask
    result = _shrink_mask(result)
  File "C:\Anaconda3\envs\dev\lib\site-packages\numpy\ma\core.py", line 1544, in _shrink_mask
    if m.dtype.names is None and not m.any():
TypeError: _any() missing 1 required keyword-only argument: 'where'
]
[autoreload of numpy failed: Traceback (most recent call last):
  File "C:\Anaconda3\envs\dev\lib\site-packages\IPython\extensions\autoreload.py", line 245, in check
    superreload(m, reload, self.old_objects)
  File "C:\Anaconda3\envs\dev\lib\site-packages\IPython\extensions\autoreload.py", line 394, in superreload
    module = reload(module)
  File "C:\Anaconda3\envs\dev\lib\imp.py", line 314, in reload
    return importlib.reload(module)
  File "C:\Anaconda3\envs\dev\lib\importlib\__init__.py", line 169, in reload
    _bootstrap._exec(spec, module)
  File "<frozen importlib._bootstrap>", line 613, in _exec
  File "<frozen importlib._bootstrap_external>", line 790, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "C:\Anaconda3\envs\dev\lib\site-packages\numpy\__init__.py", line 410, in <module>
    core.multiarray._set_madvise_hugepage(use_hugepage)
AttributeError: module 'numpy.core.multiarray' has no attribute '_set_madvise_hugepage'
]
[autoreload of numpy.testing._private.utils failed: Traceback (most recent call last):
  File "C:\Anaconda3\envs\dev\lib\site-packages\IPython\extensions\autoreload.py", line 245, in check
    superreload(m, reload, self.old_objects)
  File "C:\Anaconda3\envs\dev\lib\site-packages\IPython\extensions\autoreload.py", line 394, in superreload
    module = reload(module)
  File "C:\Anaconda3\envs\dev\lib\imp.py", line 314, in reload
    return importlib.reload(module)
  File "C:\Anaconda3\envs\dev\lib\importlib\__init__.py", line 169, in reload
    _bootstrap._exec(spec, module)
  File "<frozen importlib._bootstrap>", line 613, in _exec
  File "<frozen importlib._bootstrap_external>", line 790, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "C:\Anaconda3\envs\dev\lib\site-packages\numpy\testing\_private\utils.py", line 52, in <module>
    HAS_LAPACK64 = numpy.linalg.lapack_lite._ilp64
AttributeError: module 'numpy.linalg' has no attribute 'lapack_lite'
]
[autoreload of numpy.testing failed: Traceback (most recent call last):
  File "C:\Anaconda3\envs\dev\lib\site-packages\IPython\extensions\autoreload.py", line 245, in check
    superreload(m, reload, self.old_objects)
  File "C:\Anaconda3\envs\dev\lib\site-packages\IPython\extensions\autoreload.py", line 394, in superreload
    module = reload(module)
  File "C:\Anaconda3\envs\dev\lib\imp.py", line 314, in reload
    return importlib.reload(module)
  File "C:\Anaconda3\envs\dev\lib\importlib\__init__.py", line 169, in reload
    _bootstrap._exec(spec, module)
  File "<frozen importlib._bootstrap>", line 613, in _exec
  File "<frozen importlib._bootstrap_external>", line 790, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "C:\Anaconda3\envs\dev\lib\site-packages\numpy\testing\__init__.py", line 16, in <module>
    __all__ = _private.utils.__all__ + ['TestCase', 'run_module_suite']
NameError: name '_private' is not defined
]
Traceback (most recent call last):

  File "<ipython-input-3-48543e257c44>", line 1, in <module>
    from cdlib import algorithms #this needs to be imported on its own line... idk why it gives errors.

ImportError: cannot import name 'algorithms' from 'cdlib' (C:\Users\Andrew\AppData\Roaming\Python\Python39\site-packages\cdlib\__init__.py)
```

**Comment by andrewhong5297** [comment]
everything is working now, thank you for the quick fix @GiulioRossetti :)

**Comment by Yquetzal** [comment]
Same here, works like a charm
