### ISSUE TITLE
TypeError when using r_spectral_clustering

### ISSUE THREAD

**Issue by JoanMassachs** [GiulioRossetti/cdlib#208]
**Describe the bug**
When I execute the following code:
```
import networkx as nx
from cdlib import algorithms

algorithms.r_spectral_clustering(nx.erdos_renyi_graph(10, 0.5, seed=0))
```
I get the following error:
```
Note: to be able to use all crisp methods, you need to install some additional packages:  {'graph_tool', 'leidenalg', 'karateclub', 'wurlitzer', 'infomap'}
Note: to be able to use all overlapping methods, you need to install some additional packages:  {'ASLPAw', 'karateclub'}
Note: to be able to use all bipartite methods, you need to install some additional packages:  {'wurlitzer', 'leidenalg', 'infomap'}
Traceback (most recent call last):
  File "/home/joan/test.py", line 4, in <module>
    algorithms.r_spectral_clustering(nx.erdos_renyi_graph(10, 0.5, seed=0))
  File "/home/joan/env/lib/python3.9/site-packages/cdlib/algorithms/crisp_partition.py", line 2884, in r_spectral_clustering
    graph_eval = rsc_evaluate_graph(
  File "/home/joan/env/lib/python3.9/site-packages/cdlib/algorithms/internal/RSC.py", line 189, in rsc_evaluate_graph
    np.percentile(graph_degree, percentile)
  File "<__array_function__ internals>", line 180, in percentile
  File "/home/joan/env/lib/python3.9/site-packages/numpy/lib/function_base.py", line 4130, in percentile
    q = np.true_divide(q, 100)
TypeError: unsupported operand type(s) for /: 'NoneType' and 'int'
```

**To Reproduce**
- CDlib version: 0.2.6
- Operating System: Debian 11.2
- Python version: 3.9.2
- Version(s) of CDlib required libraries:
```
Package             Version
------------------- ----------
angel-cd            1.0.3
appdirs             1.4.4
bimlpa              0.1.2
cdlib               0.2.6
certifi             2021.10.8
charset-normalizer  2.0.12
chinese-whispers    0.8.0
cycler              0.11.0
Cython              0.29.28
decorator           5.1.1
demon               2.0.6
dynetx              0.3.1
eva-lcd             0.1.1
fonttools           4.31.2
future              0.18.2
idna                3.3
igraph              0.9.9
joblib              1.1.0
kiwisolver          1.4.2
markov-clustering   0.0.6.dev0
matplotlib          3.5.1
networkx            2.7.1
nf1                 0.0.4
numpy               1.22.3
packaging           21.3
pandas              1.4.1
Pillow              9.0.1
pip                 20.3.4
pkg-resources       0.0.0
pooch               1.6.0
PuLP                2.6.0
pyclustering        0.10.1.2
pyparsing           3.0.7
python-dateutil     2.8.2
python-igraph       0.9.9
python-Levenshtein  0.12.2
python-louvain      0.16
pytz                2022.1
requests            2.27.1
scikit-learn        1.0.2
scipy               1.8.0
seaborn             0.11.2
setuptools          44.1.1
six                 1.16.0
texttable           1.6.4
threadpoolctl       3.1.0
thresholdclustering 1.1
tqdm                4.63.1
urllib3             1.26.9
```

**Comment by andrewmagill** [comment]
The default values for this function are kind of in conflict:

see https://github.com/GiulioRossetti/cdlib/blob/master/cdlib/algorithms/crisp_partition.py#L2839

```
def r_spectral_clustering(
    g_original: object,
    n_clusters: int = 2,
    method: str = "regularized",
    percentile: int = None,
) -> NodeClustering:
```

and https://github.com/GiulioRossetti/cdlib/blob/master/cdlib/algorithms/crisp_partition.py#L2861

```
    :param percentile: percentile of the degree distribution to perform regularization. Value in [0, 100]. Mandatory if method="percentile" or "regularized", otherwise None
```

**Comment by JoanMassachs** [comment]
Oh, thanks, I should have read more carefully the documentation. I close the issue.

Maybe it would be good to throw an error saying more clear that it is the user fault, when the user gives conflictive arguments? But this would be a more general issue, maybe.
